### ISSUE TITLE
Animated GIF as an OGC API - Processes service

### ISSUE THREAD

**Issue by tomkralidis** [ECCC-MSC/msc-pygeoapi#21]
In GitLab by @alexandreleroux on Oct 4, 2019, 09:59

I wanted to suggest Animated GIF creation as a WPS service and now @rousseaulambertlp might have found a lightweight solution! In a nutshell, LP found a 70-lines code that uses mappyfile and Pillow to generate an animated GIF from a MapServer MapFile. No WMS request involved.

Sample example is [provided in section 7.3 here](https://mappyfile.readthedocs.io/en/latest/python_integration.html#animated-buffers) and the ridiculously short [Python code is here](https://mappyfile.readthedocs.io/en/latest/_downloads/0c03b548519a340df777e949424ca294/animated_buffer.py).

If we go that route, the code would need to be updated to handle TIME in the associated MapFiles, but given mappyfile is already in the mix, should be easy enough.

I still believe that a 'web form' would be useful to support internal/external users to create those animated GIFs (e.g. select/preview layers, select BBOX), but the GIF generation process itself makes a lot of sense to me as a OGC API - Processes process.

What do you think @tomkralidis ?

If eventually implemented, could be used for https://gccode.ssc-spc.gc.ca/ec-msc/public-doc/issues/66

**Comment by tomkralidis** [comment]
Closing, given we now have https://eccc-msc.github.io/msc-animet/

**Comment by alexandreleroux** [comment]
I'm ok with closing, however there is major difference ; (a) AniMet requires user-interaction, while (b) an OAProc process could be batched. Two very different use cases and capabilities.

**Comment by tomkralidis** [comment]
Can an AniMet URL be permalinked, or is that not enough?

**Comment by alexandreleroux** [comment]
Good point. We do have an internal AniMet ticket (no. 293) to assess using permalinks to trigger animation generation. The feeling at this point is what is possible via a javascript tool (AniMet) is likely not as flexible as an asynchronous API process (OGC API Processes).

Let's leave this msc-pygeoapi ticket closed and evaluate the best option as part of internal AniMet ticket. Thanks!
