### ISSUE TITLE
Provide raw data as an OGC API Processes

### ISSUE THREAD

**Issue by tomkralidis** [ECCC-MSC/msc-pygeoapi#26]
In GitLab by @alexandreleroux on Feb 20, 2020, 16:25

Ticket to discuss the possibility to provide a service sending back the raw data associated to layer ID (&TIME value, if applicable).

Actual real potential use case: layers are provided on GeoMet-Beta but not on MSC Datamart (neither dd-alpha). External users would be able to retrieve the raw data through this OGC-API-Process, which would just send back the source data untouched.

While there's a real need for this, I suspect such capability would be useful for lots of users. Our current WCS processes don't allow the retrieval of the source data untouched.

If implemented, I suspect we'd need to whitelist datasets for this new service, given we don't want to replace the Datamart with this service.

Tom indicated it could be done via pygeoapi w/STAC.

Comments / thoughts @tomkralidis @rousseaulambertlp @Dukestep  ?

**Comment by tomkralidis** [comment]
If the data is locally accessible (and we are okay with making it publically available directly, as files, in GeoMet), then we can use the STAC functionality.  Forthcoming OACov support will also allow use to simply call `/collections/{collectionId}/coverage/all` to accomplish the same for simple use cases

**Comment by alexandreleroux** [comment]
Closing given experimental STAC implementation covers this need https://api.weather.gc.ca/stac?f=html
