### ISSUE TITLE
Refactor CLI to be more logical and streamlined

### ISSUE THREAD

**Issue by Dukestep** [ECCC-MSC/msc-pygeoapi#42]
Currently, the CLI commands are organized in a way that makes it unintuitive to reach certain commands. For example, see the following commands to delete indexes related to a particular dataset:
```
msc-pygeoapi data load hydrometric-realtime clean-records
msc-pygeoapi data load hurricanes delete-index
...
```

Thes commands don't really have anything to do with loading data, per se. After some discussion in the group chat it was suggested that we could re-tool the CLI to be a little more succinct and logical. Three main commands are proposed: `load`, `manage`, `process`.

- `load` would contain subcommands for each dataset (`hurricanes`, `hydrometric-realtime`, `bulletins`, etc.) that would be used to help with tasks relating to loading data into our ES instance. For example:
```
msc-pygeoapi load hurricanes -d /path/to/data/dir/
msc-pygeoapi load hydrometric-realtime cache-stations
```
- `manage` would contain subcommands for each dataset that would allow for deleting or managing (i.e deactivating hurricane forecasts), etc. Example commands:
```
msc-pygeoapi manage hurricanes deactivate --days 2
msc-pygeoapi manage hydrometric-realtime delete-index
...
```
- `process` would contain subcommands for launching OGC API Processes and have the processes associated to their group or dataset. Example commands:
```
msc-pygeoapi process cccs raster-drill --layer <layer> --x <x_coord> --y <y_coord> --format GeoJSON
```

This seems to me a much more streamlined use of the tool as we currently use it.

Thoughts @tomkralidis, @RousseauLambertLP, @ahurka?

**Comment by tomkralidis** [comment]
I would propose `msc-pygeoapi data <dataset-name> <action> [parameters]`.  This allows top level subcommands to be based on entities mapping to pygeoapi workflow/types.

Examples:
```bash
msc-pygeoapi data hydrometric-realtime load 
msc-pygeoapi data hydrometric-realtime clean-index
msc-pygeoapi data hydrometric-realtime delete-index
```

CLI for process would stay as is.
